symfonycasts_reset_password:
  request_password_repository: 'App\User\ResetPasswordRequestRepository'
  lifetime: 3600 # Lifetime of the reset password link
  throttle_limit: 3600 # Time that needs to pass before a user can request a new reset password link